env: JRUBY_OPTS=--debug
language: ruby

cache:
  bundler: true

sudo: false

script:
  - make test
  - make validate

notifications:
  email:
    holidaysgem@gmail.com

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-head
